### ISSUE TITLE
Убрать флаг в /loop

### ISSUE THREAD

**Issue by Korepanov01** [EsQLap/vega-music-bot#6]
Предлагаю убрать флаг в /loop, если кто-то желает залупить трек, то просто пишет /loop, убирать залупливание отдельной командой вроде как смысла нет. Если человек хочет перестать слушать трек, то скорее всего просто его выключит, а не будет дослушивать текущую композицию

**Comment by EsQLap** [comment]
Флаг из /loop убирать нельзя, функция зацикливания должна включаться и выключаться в одном и том же месте. Иначе пользователю будет видна только точка входа, а точка выхода будет неоднозначной. Возможно, в будущем я подумаю, как упростить этот функционал.
